version: "3"
services:
  app:
    container_name: docker-node-mysql
    restart: always
    build: .
    volumes:
      - ./:/usr/src/app
    links:
      - mysql
    ports:
      - "8080:8080"

  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_DATABASE=lostandfound
        - MYSQL_USER=hazem
        - MYSQL_PASSWORD=hazem
        - MYSQL_ROOT_PASSWORD=hazem
    expose:
      - "3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: hazem
      PMA_PASSWORD: hazem
    ports:
      - "80:80"
    depends_on:
      - mysql
    links:
      - mysql
